### ISSUE TITLE
What type/brand socket allow for 12mm standoffs

### ISSUE THREAD

**Issue by jpconstantineau** [jpconstantineau/ErgoTravel#8]
Help by measuring the thickness of your sockets and document how much room there is left between the arduino and the bottom plate.

**Comment by viet-pham** [comment]
the digikey ultra low profile sockets leave ~2mm between the usb connector and bottom plate.  if you use the headers that come with the pro micro and pry off the black plastic, the pro micro can be soldered much closer to the pcb potentially allowing for <=9mm standoffs.

edit: i thought about this a little more and if you use go any lower than 9-10mm on the standoffs, you will need to have a cutout for the TRRS and USB cable connectors since they could potentially make contact with the bottom plate.  The cheap ebay TRRS connectors I am using will definitely make contact with the bottom plate since they're already pretty close to the bottom plate with the standoffs you sent with the kit

**Comment by jpconstantineau** [comment]
The Ultra Low Profile Sockets from Millmax will allow 12mm standoffs without much issue.
